## validate with `ExperimentHubData::makeExperimentHubMetadata()`
## (above pkg directory)
write.csv(
    file = "../extdata/metadata-tabula-muris-senis-droplet.csv",
    data.frame(
        Title = sprintf("Tabula Muris Senis droplet %s",
                        c("raw counts",
                          "processed counts",
                          "rowData",
                          "colData",
                          "UMAP",
                          "PCA")),
        Description = sprintf("%s for the Tabula Muris Senis droplet scRNA-seq dataset",
                              c("Full rectangular, block-compressed format, 1GB block size h5 file of raw counts",
                                "Full rectangular, block-compressed format, 1GB block size h5 file of processed counts",
                                "Row (gene) metadata",
                                "Column (sample) metadata",
                                "UMAP",
                                "PCA (50 PCs)")),
        RDataPath = file.path("TabulaMurisSenisData", "tabula-muris-senis-droplet",
                              c("counts.h5",
                                "processed_counts.h5",
                                "rowData.rds",
                                "colData.rds",
                                "umap.rds",
                                "pca.rds")),
        BiocVersion = "3.14",
        Genome = "GRCm38",
        SourceType = rep("HDF5", 6),
        SourceUrl = c("https://figshare.com/articles/dataset/Processed_files_to_use_with_scanpy_/8273102?file=23938934",
                      "https://figshare.com/articles/dataset/Processed_files_to_use_with_scanpy_/8273102?file=23936684",
                      "https://figshare.com/articles/dataset/Processed_files_to_use_with_scanpy_/8273102?file=23936684",
                      "https://figshare.com/articles/dataset/Processed_files_to_use_with_scanpy_/8273102?file=23936684",
                      "https://figshare.com/articles/dataset/Processed_files_to_use_with_scanpy_/8273102?file=23936684",
                      "https://figshare.com/articles/dataset/Processed_files_to_use_with_scanpy_/8273102?file=23936684"),
        SourceVersion = "",
        Species = "Mus musculus",
        TaxonomyId = "10090",
        Coordinate_1_based = NA,
        DataProvider = "The Tabula Muris Consortium",
        Maintainer = "Charlotte Soneson <charlottesoneson@gmail.com>",
        RDataClass = c("H5File", "H5File", "DFrame", "DFrame", "matrix", "matrix"),
        DispatchClass = c("H5File", "H5File", "Rds", "Rds", "Rds", "Rds"),
        stringsAsFactors = FALSE
    ),
    row.names = FALSE
)
